### PR TITLE
if-let and when-let are replaced with if-let* and when-let*

### PR DESCRIPTION
**Pull request by aaronjensen**
As of Emacs 31, `if-let` and `when-let` are deprecated. I have not fully tested these changes yet... as I'm not really sure how, so please consider this a draft/head-start.

### CODE REVIEW

**Comment by progfolio** [comment]
> As of Emacs 31, `if-let` and `when-let` are deprecated. I have not fully tested
> these changes yet... as I'm not really sure how, so please consider this a
> draft/head-start.

Thanks for the pull request, Aaron.
I updated my Emacs to the latest master this morning and ran into the byte compilation warnings while working on some other features. I have a local branch with the macros substituted which I plan on applying after I land the other features. There's still ongoing debate on the Emacs mailing list, so as annoying as the warnings are, I may wait a bit for the dust to settle.

**Comment by aaronjensen** [comment]
Ah, if there's still debate then yea, doesn't make sense. And you're welcome. I'm now running into new issues with elpa-only packages not being found by elpaca. Trying to figure out if it's a 31 issue or not...

**Comment by aaronjensen** [comment]
Just to follow up, the issue I was having was due to this:

```
(defun aj/elpaca-dev-recipe (recipe)
  "If RECIPE is part of my organization, set it up for development."
  (when-let* ((repo (plist-get recipe :repo))
              ((string-prefix-p "aaronjensen/" repo)))
    (list :protocol 'ssh :depth nil)))

(add-hook 'elpaca-recipe-functions #'aj/elpaca-dev-recipe)
```

This, for some reason, breaks elpa recipes now. I haven't sorted through why yet, so for now I'm leaving it disabled.

I'll close this PR since you have your own branch w/ the changes.

**Comment by progfolio** [comment]
Let's take a look at that in another issue thread.
I'm sure we can figure it out.

I've also gone ahead and merged the if-let/when-let branch. I don't think it should cause an regressions with the way I've been using the macros.

**Pull request closed without merging**
